// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: appoitment-service/internal/proto/appointment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppointmentStatus int32

const (
	AppointmentStatus_NEW         AppointmentStatus = 0
	AppointmentStatus_IN_PROGRESS AppointmentStatus = 1
	AppointmentStatus_DONE        AppointmentStatus = 2
)

// Enum value maps for AppointmentStatus.
var (
	AppointmentStatus_name = map[int32]string{
		0: "NEW",
		1: "IN_PROGRESS",
		2: "DONE",
	}
	AppointmentStatus_value = map[string]int32{
		"NEW":         0,
		"IN_PROGRESS": 1,
		"DONE":        2,
	}
)

func (x AppointmentStatus) Enum() *AppointmentStatus {
	p := new(AppointmentStatus)
	*p = x
	return p
}

func (x AppointmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_appoitment_service_internal_proto_appointment_proto_enumTypes[0].Descriptor()
}

func (AppointmentStatus) Type() protoreflect.EnumType {
	return &file_appoitment_service_internal_proto_appointment_proto_enumTypes[0]
}

func (x AppointmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStatus.Descriptor instead.
func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{0}
}

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{2}
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=appointment.AppointmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_NEW
}

type AppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DoctorId      string                 `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=appointment.AppointmentStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentResponse) Reset() {
	*x = AppointmentResponse{}
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentResponse) ProtoMessage() {}

func (x *AppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentResponse.ProtoReflect.Descriptor instead.
func (*AppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *AppointmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppointmentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AppointmentResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppointmentResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *AppointmentResponse) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_NEW
}

func (x *AppointmentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AppointmentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*AppointmentResponse `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appoitment_service_internal_proto_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *ListAppointmentsResponse) GetAppointments() []*AppointmentResponse {
	if x != nil {
		return x.Appointments
	}
	return nil
}

var File_appoitment_service_internal_proto_appointment_proto protoreflect.FileDescriptor

const file_appoitment_service_internal_proto_appointment_proto_rawDesc = "" +
	"\n" +
	"3appoitment-service/internal/proto/appointment.proto\x12\vappointment\"o\n" +
	"\x18CreateAppointmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17ListAppointmentsRequest\"]\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.appointment.AppointmentStatusR\x06status\"\xf0\x01\n" +
	"\x13AppointmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\tR\bdoctorId\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.appointment.AppointmentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"`\n" +
	"\x18ListAppointmentsResponse\x12D\n" +
	"\fappointments\x18\x01 \x03(\v2 .appointment.AppointmentResponseR\fappointments*7\n" +
	"\x11AppointmentStatus\x12\a\n" +
	"\x03NEW\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\b\n" +
	"\x04DONE\x10\x022\x8a\x03\n" +
	"\x12AppointmentService\x12\\\n" +
	"\x11CreateAppointment\x12%.appointment.CreateAppointmentRequest\x1a .appointment.AppointmentResponse\x12V\n" +
	"\x0eGetAppointment\x12\".appointment.GetAppointmentRequest\x1a .appointment.AppointmentResponse\x12_\n" +
	"\x10ListAppointments\x12$.appointment.ListAppointmentsRequest\x1a%.appointment.ListAppointmentsResponse\x12]\n" +
	"\x17UpdateAppointmentStatus\x12 .appointment.UpdateStatusRequest\x1a .appointment.AppointmentResponseBKZIgithub.com/fallendwn/appointment/appointment-service/internal/proto;protob\x06proto3"

var (
	file_appoitment_service_internal_proto_appointment_proto_rawDescOnce sync.Once
	file_appoitment_service_internal_proto_appointment_proto_rawDescData []byte
)

func file_appoitment_service_internal_proto_appointment_proto_rawDescGZIP() []byte {
	file_appoitment_service_internal_proto_appointment_proto_rawDescOnce.Do(func() {
		file_appoitment_service_internal_proto_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appoitment_service_internal_proto_appointment_proto_rawDesc), len(file_appoitment_service_internal_proto_appointment_proto_rawDesc)))
	})
	return file_appoitment_service_internal_proto_appointment_proto_rawDescData
}

var file_appoitment_service_internal_proto_appointment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_appoitment_service_internal_proto_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_appoitment_service_internal_proto_appointment_proto_goTypes = []any{
	(AppointmentStatus)(0),           // 0: appointment.AppointmentStatus
	(*CreateAppointmentRequest)(nil), // 1: appointment.CreateAppointmentRequest
	(*GetAppointmentRequest)(nil),    // 2: appointment.GetAppointmentRequest
	(*ListAppointmentsRequest)(nil),  // 3: appointment.ListAppointmentsRequest
	(*UpdateStatusRequest)(nil),      // 4: appointment.UpdateStatusRequest
	(*AppointmentResponse)(nil),      // 5: appointment.AppointmentResponse
	(*ListAppointmentsResponse)(nil), // 6: appointment.ListAppointmentsResponse
}
var file_appoitment_service_internal_proto_appointment_proto_depIdxs = []int32{
	0, // 0: appointment.UpdateStatusRequest.status:type_name -> appointment.AppointmentStatus
	0, // 1: appointment.AppointmentResponse.status:type_name -> appointment.AppointmentStatus
	5, // 2: appointment.ListAppointmentsResponse.appointments:type_name -> appointment.AppointmentResponse
	1, // 3: appointment.AppointmentService.CreateAppointment:input_type -> appointment.CreateAppointmentRequest
	2, // 4: appointment.AppointmentService.GetAppointment:input_type -> appointment.GetAppointmentRequest
	3, // 5: appointment.AppointmentService.ListAppointments:input_type -> appointment.ListAppointmentsRequest
	4, // 6: appointment.AppointmentService.UpdateAppointmentStatus:input_type -> appointment.UpdateStatusRequest
	5, // 7: appointment.AppointmentService.CreateAppointment:output_type -> appointment.AppointmentResponse
	5, // 8: appointment.AppointmentService.GetAppointment:output_type -> appointment.AppointmentResponse
	6, // 9: appointment.AppointmentService.ListAppointments:output_type -> appointment.ListAppointmentsResponse
	5, // 10: appointment.AppointmentService.UpdateAppointmentStatus:output_type -> appointment.AppointmentResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_appoitment_service_internal_proto_appointment_proto_init() }
func file_appoitment_service_internal_proto_appointment_proto_init() {
	if File_appoitment_service_internal_proto_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appoitment_service_internal_proto_appointment_proto_rawDesc), len(file_appoitment_service_internal_proto_appointment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appoitment_service_internal_proto_appointment_proto_goTypes,
		DependencyIndexes: file_appoitment_service_internal_proto_appointment_proto_depIdxs,
		EnumInfos:         file_appoitment_service_internal_proto_appointment_proto_enumTypes,
		MessageInfos:      file_appoitment_service_internal_proto_appointment_proto_msgTypes,
	}.Build()
	File_appoitment_service_internal_proto_appointment_proto = out.File
	file_appoitment_service_internal_proto_appointment_proto_goTypes = nil
	file_appoitment_service_internal_proto_appointment_proto_depIdxs = nil
}
